# Script realizado con Amor por:
# Alejandro Martinez Capilla
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc # Este persistent Volume para el Repositorio de Gitea
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc # Este persistent Volume para la base de datos de Gitea
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.22.3
        ports:
        - containerPort: 3000
        - containerPort: 22
        env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        - name: DB_TYPE
          value: "mysql"
        - name: HOST
          value: "mysql:3306"
        - name: NAME
          valueFrom:
            secretKeyRef:
              name: gitea-db-secret
              key: MYSQL_DATABASE
        - name: USER
          valueFrom:
            secretKeyRef:
              name: gitea-db-secret
              key: MYSQL_USER
        - name: PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-db-secret
              key: GITEA_DB_PASSWD
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: http
          initialDelaySeconds: 200
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
        - name: gitea-data
          mountPath: /data
      volumes:
      - name: gitea-data
        persistentVolumeClaim:
          claimName: gitea-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitea-db-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: gitea-db-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitea-db-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: gitea-db-secret
              key: MYSQL_DATABASE
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: gitea
spec:
  selector:
    app: gitea
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: gitea
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-db-secret
  namespace: gitea
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Z2l0ZWE=
  MYSQL_USER: Z2l0ZWE=
  MYSQL_PASSWORD: Z2l0ZWE=
  MYSQL_DATABASE: Z2l0ZWE=
  GITEA_DB_PASSWD: Z2l0ZWE=