# Script realizado con Amor por:
# Alejandro Martinez Capilla
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: production
  namespace: metallb-system
spec:
  # Production services will go here. Public IPs are expensive, so we leased
  # just 4 of them.
  addresses:
  - 10.23.23.200-10.23.23.210
  autoAssign: true