apiVersion: v1
kind: Namespace
metadata:
  name: solucion-3
spec: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solucion-3
  namespace: solucion-3
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: solucion-3
  namespace: solucion-3
  labels:
    app: solucion-3
spec:
  containers:
  - name: solucion-3
    image: httpd:latest
    volumeMounts:
    - name: nfs-para-pod
      mountPath: /usr/local/apache2/htdocs
  volumes:
  - name: nfs-para-pod
    persistentVolumeClaim:
          claimName: solucion-3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: solucion-3
  name: solucion-3
  namespace: solucion-3
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: solucion-3
  type: LoadBalancer