# Script realizado con Amor por:
# Alejandro Martinez Capilla
apiVersion: v1
kind: Namespace
metadata:
  name: solucion-2
spec: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: solucion-2
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /opt/nfs/ticveintitres1
    server: 10.23.23.18
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solucion-2
  namespace: solucion-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: solucion-2
  namespace: solucion-2
  labels:
    app: solucion-2
spec:
  containers:
  - name: solucion-2
    image: httpd:latest
    volumeMounts:
    - name: nfs-para-pod
      mountPath: /usr/local/apache2/htdocs
  volumes:
  - name: nfs-para-pod
    persistentVolumeClaim:
          claimName: solucion-2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: solucion-2
  name: solucion-2
  namespace: solucion-2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: solucion-2
  type: LoadBalancer