# Script realizado con Amor por:
# Alejandro Martinez Capilla
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
---
# Este es el PVC para los datos de Nextcloud ( ficheros...etc)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
---
# Este es el Deployment de NextCloud
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-all-in-one
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud/all-in-one:20241106_101604
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: datos
          mountPath: /mnt/data
      volumes:
      - name: datos
        persistentVolumeClaim:
          claimName: nextcloud-pvc
---
# El servicio de Nextcloud, en este caso uso LoadBalancer, pero podeis usar un Ingress y que este servicio sea un ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: nextcloud
  type: LoadBalancer