apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: ticveintitres-cluster
spec:
  hosts:
  - role: controller
    privateAddress: 10.23.23.25
    privateInterface: enp0s3
    installFlags:
    - --debug
    ssh:
      address: 10.23.23.25
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
  - role: worker
    privateAddress: 10.23.23.26
    privateInterface: enp0s3
    ssh:
      address: 10.23.23.26
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
  k0s:
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: ticveintitres-cluster
      spec:
        images:
          calico:
            cni:
              image: calico/cni
              version: v3.16.2