# Script realizado con Amor por:
# Alejandro Martinez Capilla
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: ticveintitres-cluster
spec:
  hosts:
  - role: controller
    privateAddress: 10.23.23.25
    privateInterface: enp0s3
    installFlags:
    - --debug
    ssh:
      address: 10.23.23.25
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
  - role: worker
    privateAddress: 10.23.23.26
    privateInterface: enp0s3
    ssh:
      address: 10.23.23.26
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
  k0s:
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: ticveintitres-clusteir
      spec:
        network:
          provider: calico
          clusterDomain: ticveintitres.local
          podCIDR: 10.244.0.0/24
          serviceCIDR: 10.96.0.0/24
        images:
          calico:
            cni:
              image: docker.io/calico/cni
              version: v3.16.2
            node:
              image: docker.io/calico/node
              version: v3.16.2
            kubecontrollers:
              image: docker.io/calico/kube-controllers
              version: v3.16.2