# Script realizado con Amor por:
# Alejandro Martinez Capilla
apiVersion: v1
kind: Namespace
metadata:
  name: frontal-web-rwx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontal-web-pvc-rwx
  namespace: frontal-web-rwx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontal-web-rwx
  namespace: frontal-web-rwx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nginx
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: frontal-web-rwx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: volumen
              mountPath: /usr/share/nginx/html
      volumes:
        - name: volumen
          persistentVolumeClaim:
            claimName: frontal-web-pvc-rwx
---
apiVersion: v1
kind: Service
metadata:
  name: frontal-web-svc-rwx
  namespace: frontal-web-rwx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer