apiVersion: v1
kind: Namespace
metadata:
  name: frontal-web-rwo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontal-web-pvc-rwo
  namespace: frontal-web-rwo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontal-web-rwo
  namespace: frontal-web-rwo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: frontal-web-rwo
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: volumen
              mountPath: /usr/share/nginx/html
      volumes:
        - name: volumen
          persistentVolumeClaim:
            claimName: frontal-web-pvc-rwo
---
apiVersion: v1
kind: Service
metadata:
  name: frontal-web-svc-rwo
  namespace: frontal-web-rwo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer