apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress-nginx
  namespace: metallb-system
spec:
  # Production services will go here. Public IPs are expensive, so we leased
  # just 4 of them.
  addresses:
  - 10.23.23.100/32
  autoAssign: true
  serviceAllocation:
    namespaces:
    - ingress-nginx