# Script realizado con Amor por:
# Alejandro Martinez Capilla
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configuracion
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-csi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:2024092305
        ports:
        - containerPort: 8096
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: configuracion
        - mountPath: /cache
          name: cache
        - mountPath: /media
          name: media
      volumes:
      - name: configuracion
        persistentVolumeClaim:
          claimName: configuracion
      - name: cache
        persistentVolumeClaim:
          claimName: cache
      - name: media
        persistentVolumeClaim:
          claimName: media
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-servicio
  namespace: jellyfin
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096
      name: frontal
  selector:
    app: jellyfin