apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: v1
data:
  tls.crt: Q2VydGlmaWNhdGU6CiAgICBEYXRhOgogICAgICAgIFZlcnNpb246IDMgKDB4MikKICAgICAgICBTZXJpYWwgTnVtYmVyOgogICAgICAgICAgICBkZjo2MDo0ZTo5NTo0ZTo3MDpjOTowMDplNjo0Njo3ZDoxNjo0YjpjOTozZDo0YwogICAgICAgIFNpZ25hdHVyZSBBbGdvcml0aG06IHNoYTI1NldpdGhSU0FFbmNyeXB0aW9uCiAgICAgICAgSXNzdWVyOiBDTj1FYXN5LVJTQSBDQQogICAgICAgIFZhbGlkaXR5CiAgICAgICAgICAgIE5vdCBCZWZvcmU6IERlYyAxNCAyMTowNzo0NyAyMDI0IEdNVAogICAgICAgICAgICBOb3QgQWZ0ZXIgOiBOb3YgMjAgMjE6MDc6NDcgMjEyNCBHTVQKICAgICAgICBTdWJqZWN0OiBDPUVTLCBTVD1WYWxlbmNpYSwgTD1BbGFxdWFzLCBPPVRpY1ZlaW50aXRyZXMsIE9VPUNvbW11bml0eSwgQ049bWluaW8xLnRpY3ZlaW50aXRyZXMubG9jYWwvZW1haWxBZGRyZXNzPWFkbWluQHRpY3ZlaW50aXRyZXMubG9jYWwKICAgICAgICBTdWJqZWN0IFB1YmxpYyBLZXkgSW5mbzoKICAgICAgICAgICAgUHVibGljIEtleSBBbGdvcml0aG06IHJzYUVuY3J5cHRpb24KICAgICAgICAgICAgICAgIFB1YmxpYy1LZXk6ICgyMDQ4IGJpdCkKICAgICAgICAgICAgICAgIE1vZHVsdXM6CiAgICAgICAgICAgICAgICAgICAgMDA6YzI6YTc6ZmI6Mjc6NmI6Y2Q6Zjk6MmY6M2Q6OGQ6YjM6ZTY6NjU6MmE6CiAgICAgICAgICAgICAgICAgICAgOWI6YTE6YzE6Zjk6Mjc6ZDU6OTA6NWQ6MjU6OWU6OTM6ZDU6MmU6NGY6ZTA6CiAgICAgICAgICAgICAgICAgICAgMTY6ZWI6MWI6NTQ6MjU6YTI6OTE6MDM6YmM6Yzk6Zjk6ODA6ZGI6NTg6ZDc6CiAgICAgICAgICAgICAgICAgICAgNDg6NGE6NTc6ODk6ZDY6NWE6OTg6YTY6ZjU6MDI6Njg6MjA6NTQ6ZDQ6NzQ6CiAgICAgICAgICAgICAgICAgICAgMjU6ODQ6MDA6Y2Y6OTg6OTE6NzM6ZTI6YzE6OTY6ZGU6OWU6MTI6MTY6YTY6CiAgICAgICAgICAgICAgICAgICAgNjM6Njk6NTg6OTA6OGE6NWU6M2Q6ODM6MjM6N2Q6ZTk6ZGE6YmE6MDc6NDk6CiAgICAgICAgICAgICAgICAgICAgZjU6MmM6YzA6MjY6OTY6NDA6YWI6ZjA6ZWU6MmI6NWQ6MDc6ZTI6MzE6OWU6CiAgICAgICAgICAgICAgICAgICAgMWE6MDc6NjA6NGM6M2U6NGQ6ZGM6MGE6Yjg6N2Q6NmE6N2M6ZTI6NDI6NGM6CiAgICAgICAgICAgICAgICAgICAgM2Y6MWM6N2E6Yzk6ODg6YTY6YTA6YmI6NDc6Zjc6N2U6Nzc6NjA6MDY6NmM6CiAgICAgICAgICAgICAgICAgICAgOGE6MGM6MDI6MmQ6MDg6OWY6MzM6OTE6MjE6MmI6N2I6M2M6NjY6ZmM6ZmU6CiAgICAgICAgICAgICAgICAgICAgYzc6NjI6YWE6NTE6NWQ6NTM6ZjM6YjY6ZDg6OTc6YTc6YzU6NzA6OGM6ZGY6CiAgICAgICAgICAgICAgICAgICAgODA6MjE6ZTk6MDU6ZTE6Y2M6ZDg6NzE6ZDk6ZTA6ZWU6ODg6NGI6YTg6YzI6CiAgICAgICAgICAgICAgICAgICAgNGM6YTc6MDY6OTg6ZmI6YjE6YTA6MDY6YjE6OWQ6ZjY6Mzk6OGI6NmE6NTU6CiAgICAgICAgICAgICAgICAgICAgMDM6ZDI6YWM6YTg6ZTY6N2U6Yjc6MjQ6ODg6NTg6YjA6OWE6YjQ6OTA6MzM6CiAgICAgICAgICAgICAgICAgICAgNTM6Yzg6ZWY6MmU6MTI6NjM6N2I6YjY6NDM6NTc6NGQ6Yzc6ZDg6Mzc6MzM6CiAgICAgICAgICAgICAgICAgICAgMjI6Mzk6Y2U6Mzc6ZmY6ZTY6YmM6OTM6MGM6MzQ6ZDU6MmI6MWY6ZmQ6MGU6CiAgICAgICAgICAgICAgICAgICAgMjg6Yjg6NWU6ZjQ6Y2E6YWM6Zjk6YTY6ODg6Mzg6MzI6YmU6NDY6Njg6Zjc6CiAgICAgICAgICAgICAgICAgICAgZmQ6ZWIKICAgICAgICAgICAgICAgIEV4cG9uZW50OiA2NTUzNyAoMHgxMDAwMSkKICAgICAgICBYNTA5djMgZXh0ZW5zaW9uczoKICAgICAgICAgICAgWDUwOXYzIEJhc2ljIENvbnN0cmFpbnRzOgogICAgICAgICAgICAgICAgQ0E6RkFMU0UKICAgICAgICAgICAgWDUwOXYzIFN1YmplY3QgS2V5IElkZW50aWZpZXI6CiAgICAgICAgICAgICAgICAwMzpEQjpBOTpEODpERTpEMjpGNDpCNTo5NjpERTozODpDQToyNDo4RTpGQTo3Mzo4Njo0NDpFQTo5RgogICAgICAgICAgICBYNTA5djMgQXV0aG9yaXR5IEtleSBJZGVudGlmaWVyOgogICAgICAgICAgICAgICAga2V5aWQ6NEY6RTE6MDk6RUE6QzI6NkI6QTY6M0E6Nzc6REU6ODQ6NkQ6MDA6Nzc6RDY6Qzg6RTU6NDc6QjY6QjgKICAgICAgICAgICAgICAgIERpck5hbWU6L0NOPUVhc3ktUlNBIENBCiAgICAgICAgICAgICAgICBzZXJpYWw6N0U6MDI6Mzk6MzQ6QTA6RDk6MTU6QTc6Qzg6OUY6OUQ6MDc6Q0I6RTc6NEU6Q0M6QzM6ODM6MTY6QjcKICAgICAgICAgICAgWDUwOXYzIEV4dGVuZGVkIEtleSBVc2FnZToKICAgICAgICAgICAgICAgIFRMUyBXZWIgU2VydmVyIEF1dGhlbnRpY2F0aW9uCiAgICAgICAgICAgIFg1MDl2MyBLZXkgVXNhZ2U6CiAgICAgICAgICAgICAgICBEaWdpdGFsIFNpZ25hdHVyZSwgS2V5IEVuY2lwaGVybWVudAogICAgICAgICAgICBYNTA5djMgU3ViamVjdCBBbHRlcm5hdGl2ZSBOYW1lOgogICAgICAgICAgICAgICAgRE5TOm1pbmlvMS50aWN2ZWludGl0cmVzLmxvY2FsCiAgICBTaWduYXR1cmUgQWxnb3JpdGhtOiBzaGEyNTZXaXRoUlNBRW5jcnlwdGlvbgogICAgU2lnbmF0dXJlIFZhbHVlOgogICAgICAgIDM3OjNkOmQ4OjlmOjBmOmFkOjg2OmY0OjZjOjdiOjIxOjA0OjJkOmM3OmNhOmM1OjkxOmIzOgogICAgICAgIGFhOmM5OmNjOjQxOmFjOjFiOmQ2OmY4OmE5OjQ4OjI1OmQ5OmE2OjkzOmU5OjFjOjVjOmI2OgogICAgICAgIDU4OjM4OjRkOjA4OjY1Ojk3Ojk0OjU0OjE5OmNjOmIxOjdlOjAyOjU2OjZlOmMwOjFkOjdjOgogICAgICAgIGZlOjgzOjI2OmNmOmY3OmQ3OjNjOmYwOjA5OmRjOmM2OjA3OjdmOmY1OmI4OjZhOjUwOjcwOgogICAgICAgIDMwOmMwOjA5OmZkOmViOmUzOmFjOmQ1OjlkOmFhOjg2OmI1OjRmOmUzOmVmOmRmOmU0OmU3OgogICAgICAgIGUwOjhlOmU2Ojc4OjlkOmVhOmE5OjI4OjEwOjcyOjQxOjFkOjRhOmY1OjUwOmJiOmZlOmU0OgogICAgICAgIGMxOmEyOmExOjFjOmQ1OjY1OmNiOmFiOjE1OmMzOjg0OmUxOjllOjBhOmE2OmQxOjMyOmQxOgogICAgICAgIDEzOmY2OjM3Ojc4OjFjOmQ2OjEyOmRkOjQ3OjhhOmMwOjQ1OjgyOjc3OmI5Ojc3OjA1OjEzOgogICAgICAgIDRmOjFjOmY0OmVjOjcxOjIwOjBkOjAwOmJiOjM5OjZjOmIwOjFjOmJmOjc4OjRhOmJiOmE4OgogICAgICAgIGI3OjcxOjIzOjY1OjViOmQ3OmE2OmIyOjRhOjU0OjExOjIzOmJjOjY5OjYxOmE2OjFkOjBmOgogICAgICAgIDM0OjFlOjg4OjM3OmQ3OjlhOjAyOjRkOmFiOjcyOjE5OmU1OmJmOjc1OjFiOmJiOjZmOjU2OgogICAgICAgIGFmOjMwOmViOjBlOjQ1OjkwOmU0Ojg5OjE4OmNjOjA2OjhhOjNmOjI1OmRlOmNlOmY0OjQxOgogICAgICAgIGJhOmRlOjJkOjI2OjVlOmM3OjVlOmNlOjU0OjgzOjFhOjEyOmYyOjg2OmYzOmUwOjQwOjU3OgogICAgICAgIGE1Ojg5OmZiOjE3OjZlOjMyOmZjOjhjOjZmOjE2OjU3OmJkOjkzOmNhOjJjOjIyOmZhOjU5OgogICAgICAgIDVkOmFlOjM1OmEzCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlFR3pDQ0F3T2dBd0lCQWdJUkFOOWdUcFZPY01rQTVrWjlGa3ZKUFV3d0RRWUpLb1pJaHZjTkFRRUxCUUF3CkZqRVVNQklHQTFVRUF3d0xSV0Z6ZVMxU1UwRWdRMEV3SUJjTk1qUXhNakUwTWpFd056UTNXaGdQTWpFeU5ERXgKTWpBeU1UQTNORGRhTUlHdE1Rc3dDUVlEVlFRR0V3SkZVekVSTUE4R0ExVUVDQXdJVm1Gc1pXNWphV0V4RURBTwpCZ05WQkFjTUIwRnNZWEYxWVhNeEZqQVVCZ05WQkFvTURWUnBZMVpsYVc1MGFYUnlaWE14RWpBUUJnTlZCQXNNCkNVTnZiVzExYm1sMGVURWpNQ0VHQTFVRUF3d2FiV2x1YVc4eExuUnBZM1psYVc1MGFYUnlaWE11Ykc5allXd3gKS0RBbUJna3Foa2lHOXcwQkNRRVdHV0ZrYldsdVFIUnBZM1psYVc1MGFYUnlaWE11Ykc5allXd3dnZ0VpTUEwRwpDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRENwL3NuYTgzNUx6Mk5zK1psS3B1aHdma24xWkJkCkpaNlQxUzVQNEJickcxUWxvcEVEdk1uNWdOdFkxMGhLVjRuV1dwaW05UUpvSUZUVWRDV0VBTStZa1hQaXdaYmUKbmhJV3BtTnBXSkNLWGoyREkzM3Aycm9IU2ZVc3dDYVdRS3Z3N2l0ZEIrSXhuaG9IWUV3K1Rkd0t1SDFxZk9KQwpURDhjZXNtSXBxQzdSL2QrZDJBR2JJb01BaTBJbnpPUklTdDdQR2I4L3NkaXFsRmRVL08yMkplbnhYQ00zNEFoCjZRWGh6Tmh4MmVEdWlFdW93a3luQnBqN3NhQUdzWjMyT1l0cVZRUFNyS2ptZnJja2lGaXdtclNRTTFQSTd5NFMKWTN1MlExZE54OWczTXlJNXpqZi81cnlURERUVkt4LzlEaWk0WHZUS3JQbW1pRGd5dmtabzkvM3JBZ01CQUFHagpnY2t3Z2NZd0NRWURWUjBUQkFJd0FEQWRCZ05WSFE0RUZnUVVBOXVwMk43UzlMV1czampLSkk3NmM0WkU2cDh3ClVRWURWUjBqQkVvd1NJQVVUK0VKNnNKcnBqcDMzb1J0QUhmV3lPVkh0cmloR3FRWU1CWXhGREFTQmdOVkJBTU0KQzBWaGMza3RVbE5CSUVOQmdoUitBamswb05rVnA4aWZuUWZMNTA3TXc0TVd0ekFUQmdOVkhTVUVEREFLQmdncgpCZ0VGQlFjREFUQUxCZ05WSFE4RUJBTUNCYUF3SlFZRFZSMFJCQjR3SElJYWJXbHVhVzh4TG5ScFkzWmxhVzUwCmFYUnlaWE11Ykc5allXd3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRGM5Mko4UHJZYjBiSHNoQkMzSHlzV1IKczZySnpFR3NHOWI0cVVnbDJhYVQ2UnhjdGxnNFRRaGxsNVJVR2N5eGZnSldic0FkZlA2REpzLzMxenp3Q2R6RwpCMy8xdUdwUWNEREFDZjNyNDZ6Vm5hcUd0VS9qNzkvazUrQ081bmlkNnFrb0VISkJIVXIxVUx2KzVNR2lvUnpWClpjdXJGY09FNFo0S3B0RXkwUlAyTjNnYzFoTGRSNHJBUllKM3VYY0ZFMDhjOU94eElBMEF1emxzc0J5L2VFcTcKcUxkeEkyVmIxNmF5U2xRUkk3eHBZYVlkRHpRZWlEZlhtZ0pOcTNJWjViOTFHN3R2VnE4dzZ3NUZrT1NKR013RwppajhsM3M3MFFicmVMU1pleDE3T1ZJTWFFdktHOCtCQVY2V0oreGR1TXZ5TWJ4Wlh2WlBLTENMNldWMnVOYU09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRRENwL3NuYTgzNUx6Mk4KcytabEtwdWh3ZmtuMVpCZEpaNlQxUzVQNEJickcxUWxvcEVEdk1uNWdOdFkxMGhLVjRuV1dwaW05UUpvSUZUVQpkQ1dFQU0rWWtYUGl3WmJlbmhJV3BtTnBXSkNLWGoyREkzM3Aycm9IU2ZVc3dDYVdRS3Z3N2l0ZEIrSXhuaG9ICllFdytUZHdLdUgxcWZPSkNURDhjZXNtSXBxQzdSL2QrZDJBR2JJb01BaTBJbnpPUklTdDdQR2I4L3NkaXFsRmQKVS9PMjJKZW54WENNMzRBaDZRWGh6Tmh4MmVEdWlFdW93a3luQnBqN3NhQUdzWjMyT1l0cVZRUFNyS2ptZnJjawppRml3bXJTUU0xUEk3eTRTWTN1MlExZE54OWczTXlJNXpqZi81cnlURERUVkt4LzlEaWk0WHZUS3JQbW1pRGd5CnZrWm85LzNyQWdNQkFBRUNnZ0VBTmIxRWREeXA3NnBnRnZmY21uOXAyZjJBT01RWUIrOHoyV0pZVjhybzZOMXgKbkxaRnpMOVpEMTNJc0wwMmd2ZXA0UmkvM2cvMEt5VUo1bUZ1WGdRUFMvS1VDTDBqVnJCVEZCZTVpRUxnSEtNcAoza04xSnBPeEdnUU1BTi9IaDJHeFZtR2FiU09aQ2RPNUllSXZDbUJhYUVkSXNKWnJySnY2TEhXbG4rbElwSXNkCkFobWptYlpRcVF4VzJCdDBPSFZKUmRTTzNiQ25TVTFYaTkrbXA1WnlUZTJoWVl0d21VZTJYL0FoWk1CWloyamYKdnBYMmJMcVNKWS8vNkdGREN4VExya0kvd0lDZVVoRm90cHZHSHc0VEFKWHh5SjFwcmU4ODRIc0tRMDVxR0E5OQprK2dXVkhIZEtvYnhSaUVxU0laUmNVUmFzNWtYbWFOcWtLRFNYMTdGY1FLQmdRRDBPckVGZVp6bDh1SDBydmMvClF2cFpka3pxUTJsNGVRSnpWK2N2dWR4dmZPU0E3VUcwOVZ0Y1REcktmVnVseUZ0L1NtYzRvemRtbXZmdnJzSngKY3N5WXZlbmNWQW1USUNhMTFzT1JZd05ROHRuaFJsQm94Z3FKdXlOT1hoZk9UcFVGKzZNK0dldlZjalM3VkUzbgpBR1FSaHczQ1d0MXdpNTdUUmd1dDZmQWpvd0tCZ1FETUNhZTlQOU95VUJoZWJ1NmY0UFNxWXMyYXQ3R3RkUzk1CmZSaG1xK0Y4d29Ca2FHaTM0T3dEZmlIblpuOEZiYWNFSnV4MTBXVm4xTkVaVnJjTmIrTlBCaWM5Qk4xUHFjdHYKeTBPekwzcXhvMEFXUEdVMU9oeERLSThqTFpENXlUMmg4a2JZdWEwc1Q5dVJDRWQyWmdZK2lIYm5wU3VBaFRwYQpSUW9OSnltaEdRS0JnRWZISEJHczNVVGpyaTdZWVVnUmFqeHl2VVk0Uzc0aGFtdjEwTGRCRzUwVWlwK3RteHNRCjVTbnFLWGtyZ0l6bnBxUnhmSWF6eVd0NWJoYmVPTDFZN1BLVEZqRXY3YVIwMVl1cHM4NTkyQktwWFFtTlBjS2QKT2FtaSsweGo4UUVzTFRZVjc3TW5zUjBKTktBOXRhdUhmT0Y5M0xoYk5pdUdqVVl3bHV3bERmT2JBb0dBU0NYcAo0R3VmYWVBVW5kL1FGVXl3ZDBkMHVJN1lEeVB1NDZDdWJpKzlEaWFneStCM2x2Mjd0d2gwNktRL3FpVzU5eWZrCldVenY5S1UyUXlWOG1RM0ZiUDRhQmVPZ2RqanVMTnZOVnFFbFc0Y0VkRmhxMlVWeEZQWlVsdlhYMjl1akpZN00KS25xTmw2dXRVajJCTjRhZ0VxQ2ltd3EydFQxbkF1Q0N5MS9id3BFQ2dZQUFtUktJNHAxdVlIeDFFWUlXeWR5bwplTFFuc25rSTNoY3RFVXhHVjJKdTFnVlNkdCt6S0h4VHVUZktjNDlJYldKK3dxZ0hPOE04T29PcDBBay9JcEtFCkI2eForRkh4TS9kOGRIRGZ4Uzl2L1RkVE05UzVTQjlsQTRFMnJEeTdFeHA1YXMvZzZPdUMvd0VrWDNJRkhmbGkKR0hWR0pydlNINExlRmFoTmhsWUxHUT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURUVENDQWpXZ0F3SUJBZ0lVZmdJNU5LRFpGYWZJbjUwSHkrZE96TU9ERnJjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZqRVVNQklHQTFVRUF3d0xSV0Z6ZVMxU1UwRWdRMEV3SUJjTk1qUXhNakUwTWpBME5EQTFXaGdQTWpFeQpOREV4TWpBeU1EUTBNRFZhTUJZeEZEQVNCZ05WQkFNTUMwVmhjM2t0VWxOQklFTkJNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFvMGhEZUxBSExhRkJ0R1NkSDdlRDU5aitDT1gyeFRXM0Z2RUoKNi9ETTNGNVUyMXNjcDhJQ3VMN3dXVTlkZ3J1MUFUQklRaXMrbWhsTEZ4N1RJYklpa2JJLzBqRy9DZWFoZnJwQQpDQSt6VUY3eEUrdWEvUDFUVjcvOWlqV2JoR1YzZG9tcTd4a21tbWxJa2J6ZlRHaW1TaktXNThqd000WURMMTQwCnhxWDhMMVNxRkFZdHFPZTJIa1ZSTFpWelBqVTRKUWxYWTlDNUI2RThxNWk1Rk1NWVYyajBxcmF3ZWprYXl5b2sKWkdwYjJJcmhkMEdrQnl1T1N4MHZmYUZXdVNIM1UvQzdMRzYxbDZFTkhENGJsZEM4WnFhUVVDM1ppdTRwQTEvZQpuVnplVzJUZFc2RDRPQVJHd2tqM2dHbjdMZ0xCZ3JESHZGUmQ2RmdDbkdnbktRV3ROd0lEQVFBQm80R1FNSUdOCk1Bd0dBMVVkRXdRRk1BTUJBZjh3SFFZRFZSME9CQllFRkUvaENlckNhNlk2ZDk2RWJRQjMxc2psUjdhNE1GRUcKQTFVZEl3UktNRWlBRkUvaENlckNhNlk2ZDk2RWJRQjMxc2psUjdhNG9ScWtHREFXTVJRd0VnWURWUVFEREF0RgpZWE41TFZKVFFTQkRRWUlVZmdJNU5LRFpGYWZJbjUwSHkrZE96TU9ERnJjd0N3WURWUjBQQkFRREFnRUdNQTBHCkNTcUdTSWIzRFFFQkN3VUFBNElCQVFBaDZPcC8vREkwT3dLd2JhdVFLbCtta1R1Nk5mWmM5Ui95ekJubEgraFIKL3NsSU5rTGtzMDBEbXEzYWtrZWFOQnh1L2RaUm13NUJ6NnpFTW81eS9iOWJzcUIzRHJ0Wi9xUkJ5SmFtZllXZgpTQy9UM2dWSTNmcnFxUkp5Mk9XZzk3RW04bXlheGVCcGhDRExZRTBHaXQrN0RxbW00WXBtYzcxY0NkYjBjbHFNCnpub1RSSTRGb213ZVJrTjJqOVdUOW1BQ09tS3NUY0N0SmN3NWpDOExJRS8zeHd2NjYrUkdsNkZyYnpaQWtaMWYKaFBZUWJ5NVd6Zy9GR2dwZENjUDRzUUFmMlpFTkZjaERIbXJLUExWSXNDZkptaVdsK0J6WmM0ZkpjenNPMjNqdwovbUZhT3NXUi95MnFJVFp4d2tRSXJlcE4vQi90eUg3MkFzckZFRGFQMGRRdAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
kind: Secret
metadata:
  name: minio-tls
  namespace: minio
type: kubernetes.io/tls
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio
  labels:
     app: minio
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio
  replicas: 3
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        env:
        - name: MINIO_REGION_NAME
          value: "minio"
        - name: MINIO_ACCESS_KEY
          value: "ticveintitres"
        - name: MINIO_SECRET_KEY
          value: "ticveintitres"
        image: minio/minio:latest
        args:
        - server
        - http://minio-0.minio.minio.svc.cluster.local/datos
        - http://minio-1.minio.minio.svc.cluster.local/datos
        - http://minio-2.minio.minio.svc.cluster.local/datos
        - --console-address=:9001
        ports:
        - containerPort: 9000
          protocol: TCP
          name: api
        - containerPort: 9001
          protocol: TCP
          name: console
        volumeMounts:
        - name: datos
          mountPath: /datos
  volumeClaimTemplates:
  - metadata:
      name: datos
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio
spec:
  type: ClusterIP
  ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
  labels:
   app: minio
spec:
  clusterIP: None
  ports:
    - port: 9000
      name: minio
    - port: 9001
      name: console
  selector:
    app: minio
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: minio
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 5t
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - minio1.ticveintitres.local
      secretName: minio-tls
  rules:
    - host: minio1.ticveintitres.local
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: minio-service
                port:
                  number: 9001